# Enable all features during release
enable-all-features = true

# Pre-release checks
pre-release-commit-message = "chore: release {{crate_name}} v{{version}}"

# Tag settings
tag-message = "chore: release v{{version}}"
tag-prefix = "v"

# Push and publish settings
push = true
publish = true
