# Enable all features during release
enable-all-features = true

# Pre-release checks
pre-release-commit-message = "chore: release {{crate_name}} v{{version}}"
pre-release-replacements = [
  { file = "README.md", search = "fireblocks-solana-signer = \"[^\"]*\"", replace = "fireblocks-solana-signer = \"{{version}}\"" },
  { file = "README.md", search = "fireblocks-solana-signer@[^\\s]*", replace = "fireblocks-solana-signer@{{version}}" },
]

# Tag settings
tag-message = "chore: release v{{version}}"
tag-prefix = "v"

# Push and publish settings
push = true
publish = true
